package com.ygaps.travelapp.manager

object Constant {
    const val tokenExpire = 24*60*60
    const val BASE_URL = "http://35.197.153.192:3000"
    const val ggServerClientID = "1013546197046-2amvjqr03i3po0u9qructlrj8vr2knbf.apps.googleusercontent.com"
    const val ggclientSecret = "fjVoYy4505lqYHrsUf4mTdEH"
    const val ggMapApiKey = "AIzaSyBTPGt6wHibzdpuwi31X9qNwHosuyu0GEg"
    val provinceList: ArrayList<String> = arrayListOf("Hồ Chí Minh",
        "Hà Nội",
        "Đà Nẵng",
        "Bình Dương",
        "Đồng Nai",
        "Khánh Hòa",
        "Hải Phòng",
        "Long An",
        "Quảng Nam",
        "Bà Rịa Vũng Tàu",
        "Đắk Lắk",
        "Cần Thơ",
        "Bình Thuận  ",
        "Lâm Đồng",
        "Thừa Thiên Huế",
        "Kiên Giang",
        "Bắc Ninh",
        "Quảng Ninh",
        "Thanh Hóa",
        "Nghệ An",
        "Hải Dương",
        "Gia Lai",
        "Bình Phước",
        "Hưng Yên",
        "Bình Định",
        "Tiền Giang",
        "Thái Bình",
        "Bắc Giang",
        "Hòa Bình",
        "An Giang",
        "Vĩnh Phúc",
        "Tây Ninh",
        "Thái Nguyên",
        "Lào Cai",
        "Nam Định",
        "Quảng Ngãi",
        "Bến Tre",
        "Đắk Nông",
        "Cà Mau",
        "Vĩnh Long",
        "Ninh Bình",
        "Phú Thọ",
        "Ninh Thuận",
        "Phú Yên",
        "Hà Nam",
        "Hà Tĩnh",
        "Đồng Tháp",
        "Sóc Trăng",
        "Kon Tum",
        "Quảng Bình",
        "Quảng Trị",
        "Trà Vinh",
        "Hậu Giang",
        "Sơn La",
        "Bạc Liêu",
        "Yên Bái",
        "Tuyên Quang",
        "Điện Biên",
        "Lai Châu",
        "Lạng Sơn",
        "Hà Giang",
        "Bắc Kạn",
        "Cao Bằng")
}